name: Dockerize and Push to Infra-Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Dockerize and Push to Infra-Repo Action
        uses: fantasyflip/k8s-build-transfer@v1.2.0
        with:
          node-version: 18
          infra-repo: "fantasyflip/k8s-infra"
          gh-token: ${{ secrets.GH_TOKEN }}
          gh-email: "katzenberger.ph+github@gmail.com"
          namespace: "munchcoach"
          app-name: "munchcoach-app"
